Update handler to produce a full trace with child spans
honeycombio/chef-handler-honeycomb pull request #10
Opened 2022-08-30 22:05 UTC by tdarwin

## Which problem is this PR solving?

The current version of the handler does not produce what Honeycomb recognizes as a trace, so there is no waterfall view of processes, access to use the node object in queries, and very minimal bubble up capabilities.

## Short description of the changes

This updates the product to be a full trace, where the compile, converge, and handler phases are all shown as child spans, and the converge phase is broken down into spans per cookbook, recipe, and resource.

All objects have access to a subset of the node object that make bubble-up and querying more interesting, and users are provided with a mechanism to ensure that node attributes/objects that they care about can be included in that data as well.

## Notes

There's some funky code to make this work as a handler that's part of a cookbook, but it does. If I were committing this as something I wanted to be part of Chef itself, there would be cleaner ways to do certain things.

## Resulting Images

Here are some screen captures of this handler in action in waterfall mode, query + heatmap, and bubble-up:
![image (4)](https://user-images.githubusercontent.com/162021/187552015-8a315acf-fb29-40f2-8451-386bf450ca02.png)
![image (3)](https://user-images.githubusercontent.com/162021/187552016-f9a38f73-eb4f-4d7f-9a77-82970c966231.png)
![image (2)](https://user-images.githubusercontent.com/162021/187552020-04989c12-518c-4cc2-8d60-2928807656e9.png)
![image (1)](https://user-images.githubusercontent.com/162021/187552022-db3406f9-37ee-42a4-85a4-ecb148efc5df.png)

2022-08-30 22:06 UTC, tdarwin commented
As a note. I've only tested this with Chef/CINC client version 17.10 so far.

2022-09-06 10:24 UTC, MikeGoldsmith requested changes
Looks really good, thanks @tdarwin 👍🏻 

I've left some feedback to remove an unused func, remove commented out code and styling things.

2022-09-06 10:24 UTC, MikeGoldsmith commented on README.md
> +** details: [https://docs.chef.io/config_rb_client.html](https://docs.chef.io/config_rb_client.html)
```suggestion
** See Chef's [config client](https://docs.chef.io/config_rb_client.html)
```

2022-09-06 10:24 UTC, MikeGoldsmith commented on libraries/honeycomb.rb
> +        h = {
nit: try to avoid single character variable names. This could be `node_data`.

2022-09-06 10:24 UTC, MikeGoldsmith commented on libraries/honeycomb.rb
> +          # 'chef.complete_node' => ::Chef::DSL::RenderHelpers::render_json(run_status.node),
Can this be removed?

2022-09-06 10:24 UTC, MikeGoldsmith commented on libraries/honeycomb.rb
> +        h = {
Could you add the hash instead of doing a merge?

```ruby
span_data['meta.span_type'] = 'child'
```

2022-09-06 10:24 UTC, MikeGoldsmith commented on libraries/honeycomb.rb
> +    def generate_trace_context(type)
Doesn't look like this is used, can be remove.

2022-09-06 10:24 UTC, MikeGoldsmith commented on recipes/default.rb
> +  # compliance_span_id = SecureRandom.hex(8)
Could be removed?

2022-09-06 10:24 UTC, MikeGoldsmith commented on recipes/default.rb
> +    # Chef::Handler::JsonFile(@run_status, path: '/tmp/reports')
Remove?

2022-09-06 10:24 UTC, MikeGoldsmith commented on recipes/default.rb
> +    # Chef::Handler::JsonFile(@run_status, path: '/tmp/reports')
Remove?

2022-09-06 10:24 UTC, MikeGoldsmith commented on libraries/honeycomb.rb
> +VERSION="1.0.0"
We'll create a subsequent release PR to bump the version.

```suggestion
VERSION="0.1.1"
```

2022-09-08 00:33 UTC, tdarwin commented
@MikeGoldsmith Thanks for all the suggestions and tweaks and nit-picks. I'll put out another commit soon to clean stuff up. might not be until Friday when I'm back from this conference.

2022-09-08 09:03 UTC, MikeGoldsmith approved these changes
This looks good, thanks @tdarwin 👍🏻

2022-09-08 09:04 UTC, merged